### ISSUE TITLE
Missing Release

### ISSUE THREAD

**Issue by Sarkie** [eobermuhlner/csv2chart#17]
@eobermuhlner There's no releases, I know this project is quite old but just wondering if you meant to

**Comment by eobermuhlner** [comment]
This is unfortunately correct. 
Somehow I never got around to finish the planned release 0.1

I have now created a release 0.0.1 with the current state (not much documentation though).

Hope this helps

**Comment by Sarkie** [comment]
Thanks @eobermuhlner just it was top on DDG, so thought I'd try.

I did try a gradlew build on Windows and it fails on testing the images, but not sure if you care to look at it

Thanks!
