### ISSUE TITLE
gradlew build fails on windows but works on mac

### ISSUE THREAD

**Issue by Sarkie** [eobermuhlner/csv2chart#18]
![image](https://user-images.githubusercontent.com/283203/84487932-643d4e80-ac97-11ea-8a25-5cd961e30bd7.png)

The release works fine, but it fails the test on Windows 10 / Java 1.8

[test.zip](https://github.com/eobermuhlner/csv2chart/files/4769911/test.zip)

This isn't a priority at all, but just in case it piqued your interest to fix it.

**Comment by eobermuhlner** [comment]
The test on the reference platform (currently Windows) generates chart images and compares with previously generated reference images.

Unfortunately the rendering in Java is very dependent on operating system, installed fonts and other unknown factors.

I have regenerated the images on my newest Windows PC (verifying each for correctness), but unfortunately there is no guarantee that they will work correctly on different machines.

After a failed test you can look at the `ch.obermuhlner.csv2chart\src\test\resources\out_images` folder and check the generated images, comparing them with the reference files in the filter `ch.obermuhlner.csv2chart\src\test\resources\ref_images`).

**Comment by Sarkie** [comment]
@eobermuhlner yeah I checked myself and they were totally different, just thought I'd raise it just in case.
But thank you, it is perfect for my needs in the current and thank you for all your work!
