### ISSUE TITLE
I am not able to plot the chart with this utility

### ISSUE THREAD

**Issue by Blason** [eobermuhlner/csv2chart#19]
Hi Team,

Is this project still being supported? I am not able to plot the data using this utility and here is my data

# csv2chart.title=Applox
# csv2chart.chart=auto
# csv2chart.out.format=png
applox-ips-data,165.22.223.180
applox-ips-data,217.215.125.101
applox-ips-data,45.227.254.54
applox-ips-data,192.241.196.120
applox-ips-data,192.241.198.9
applox-ips-data,109.237.98.226
applox-ips-data,198.199.95.197
applox-ips-data,192.241.212.118
applox-ips-data,201.19.91.93
applox-ips-data,35.87.134.40
applox-ips-data,185.81.157.9
applox-ips-data,147.182.144.7
applox-ips-data,109.237.97.180
applox-ips-data,103.145.255.142
applox-ips-data,45.227.254.54
applox-ips-data,35.193.197.89
applox-ips-data,198.199.94.63
applox-ips-data,192.241.208.143

 ./csv2chart ../../test.csv

**Comment by Blason** [comment]
Wrong logic for plotting data!!

**Comment by eobermuhlner** [comment]
What would you expect to be plotted?

The tool `csv2chart` assumes that you give it numerical data to plot.
Your data looks like IP addresses, which cannot be shown as the usual barchart, piechart, xyline, ...

**Comment by Blason** [comment]
Yes - I thought that hence I closed the issue since this logic is not
possible

**Comment by eobermuhlner** [comment]
Ah cool. I had not realized that you already closed the issue.

Good luck with `csv2chart` for other use cases.
